version: "3.8"

services:

  app:
    build:
      context: ./docker/php
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    depends_on:
      - postgres
      - redis
      - soketi
    networks:
      - app-network

  nginx:
    image: nginx:stable
    container_name: nginx_server
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: chat
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  soketi:
    image: quay.io/soketi/soketi:latest-16-alpine
    container_name: chat-soketi-1
    ports:
      - "6001:6001"
    environment:
      SOKETI_DEBUG: '1'
      SOKETI_DEFAULT_APP_ID: 'local'
      SOKETI_DEFAULT_KEY: 'local'
      SOKETI_DEFAULT_SECRET: 'local'
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
